### PR TITLE
Auto reconnect

### PR DESCRIPTION
**Pull request by wds4**
Trigger an automatic reconnection attempt whenever a relay disconnects. By default, this functionality is off. Activate it using `autoReconnect` like this:

```
<NostrProvider relayUrls={relayUrls} debug={true} autoReconnect={true} >
  <App />
</NostrProvider>
```

I'm wondering whether I should move the logic for triggering the reconnection attempt to `OnDisconnectFunc`. Let me know if that would make more sense. We might want to make the logic more complex, e.g. stop attempting after N failed attempts. See [this issue](https://github.com/t4t5/nostr-react/issues/8#issuecomment-1396374993) for my longer discussion.

### CODE REVIEW

**Comment by t4t5** [comment]
This is great, thanks for the PR! 🙌 

We probably want to have a default max number of retries to prevent infinite loops too.

One thing I'm not sure about is whether `onDisconnect` should be called every time a disconnect happens (even if it successfully reconnects shortly after), or if it should only be called once the max retries have failed (so that the client can show an error message). 

I think I'm leaning towards the latter, what are your thoughts?

**Comment by wds4** [comment]
Are you wondering when to call `onDisconnectCallback` within the `relay.on("disconnect", () => {` block? That calls `OnDisconnectFunc `. Perhaps we could call `OnDisconnectFunc ` after each individual disconnect (as it does now) but make a new function called something like `OnMaxDisconnectsFunc` after the max retries have been reached?

**Comment by wds4** [comment]
We could include a parameter like this:
```
<NostrProvider relayUrls={relayUrls} debug={true} autoReconnect={true} reconnectAttemptLimit={reconnectAttemptLimit} >
  <App />
</NostrProvider>
```
btw we will need a way to keep track of disconnects and other relay stats, along the lines of [this](https://github.com/v0l/snort/blob/main/src/Nostr/ConnectionStats.ts).

**Comment by wds4** [comment]
I'm closing this pull request, as I find that `onDisconnectCallback` as described by @aussedatlo [here](https://github.com/t4t5/nostr-react/pull/14#issuecomment-1418245578) solves the issue of auto reconnect, and has the added benefit that it will be straightforward for relay-specific stats like number of disconnects to be managed completely by the client without relying on `nostr-react` to do it.

**Pull request closed without merging**
